server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail/positions_s.yaml

# clients:
#  - url: http://localhost:3100/loki/api/v1/push

forwarder:
  listen_port: 9081
  tls_config:
    cert_file: /tmp/promtail/auth.crt
    key_file: /tmp/promtail/auth.key

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
